name: Sauna Reservation Bot

on:
  schedule:
    - cron: '30 6 * * 1'
  workflow_dispatch:

jobs:
  reserve:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: ghcr.io/puppeteer/puppeteer:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Puppeteer script
        run: node index.js
        env:
          GYM_USERNAME: ${{ secrets.GYM_USERNAME }}
          GYM_PASSWORD: ${{ secrets.GYM_PASSWORD }}
          TOTP_SECRET: ${{ secrets.TOTP_SECRET }}